/**
 * 多语言配置文件
 * 支持中文和英文
 */

const Languages = {
    // 中文（默认）
    zh: {
        // 应用标题和基本界面
        appTitle: "📝 Todo List",
        settingsBtn: "设置中心",
        settings: "设置",
        save: "保存",
        cancel: "取消",
        confirm: "确认",
        delete: "删除",
        edit: "编辑",
        view: "查看",
        close: "关闭",
        loading: "加载中...",
        itemRequired: "请填写必填项！",
        
        // 任务相关
        task: "任务",
        tasks: "任务",
        newTask: "新建任务",
        editTask: "编辑任务",
        copyTask: "复制任务",
        taskTitle: "任务标题",
        taskDescription: "任务描述",
        taskPriority: "优先级",
        taskCategory: "分类",
        taskDueDate: "截止日期",
        taskCreateTime: "创建时间",
        taskUpdateTime: "更新时间",
        taskTags: "标签",
        taskTag: "标签",
        taskTagsHint: "（选择或添加标签）",
        taskStatus: "状态",

        // 任务详情
        noTaskTags: "无标签",
        noTaskDescription: "无描述",

        // 任务附件
        taskAttachments: "附件",
        noTaskAttachments: "无附件",
        attachment: "附件",
        attachmentEmpty: "暂无附件",
        attachmentUploadFile: "上传文件",
        attachmentAddLink: "添加链接",
        attachmentAddFolder: "关联文件夹",
        folderAddUnsupportedOnMobile: "移动端不支持关联文件夹",
        folderOpenUnsupportedOnMobile: "移动端不支持打开任务关联的文件夹",
        folderOpenFailed: "打开文件夹失败，文件夹可能已被移动或删除",
        attachmentMaxReached: "最多只能添加 {count} 个附件",
        attachmentTooLarge: "单个附件不能超过 10MB，已忽略 {count} 个文件",
        attachmentLinkRequired: "请输入链接地址",
        attachmentLinkInvalid: "链接地址格式不正确",
        attachmentOpenFailed: "打开附件失败",
        attachmentOpenFallback: "无法直接打开附件，已为你打开文件所在目录，请手动打开",
        attachmentRevealFailed: "无法打开文件所在目录",
        attachmentOptionalHint: "（可选，最多 5 个，单个 10MB 以内）",
        attachmentAddLinkTitle: "添加在线链接",
        attachmentLinkName: "链接名称",
        attachmentLinkNameHint: "（可选，默认使用链接地址）",
        attachmentLinkNamePlaceholder: "请输入链接名称",
        attachmentLinkUrl: "链接地址",
        attachmentAdd: "添加",

        // 优先级
        priorityHigh: "高优先级",
        priorityMedium: "中优先级", 
        priorityLow: "低优先级",
        priorityNone: "无优先级",
        // 优先级-图标
        high: "高",
        medium: "中",
        low: "低",
        none: "无",
        
        // 状态
        statusCompleted: "已完成",
        statusUncompleted: "未完成",
        statusPending: "未完成未逾期",
        statusOverdue: "未完成已逾期",
        
        // 统计信息
        statsTotalTasks: "总任务",
        statsCompletedTasks: "已完成",
        statsUnCompletedTasks: "未完成",
        statsCompletionRate: "完成率",
        statsLastUpdateTime: "最后更新",
        statsTodayCompletedTasks: "今日已完成",
        statsOverDueDateTasks: "已逾期",
        statsCategories: "分类数",
        statsAllTime: "全部时间",
        
        // 分类管理
        categories: "分类",
        allCategories: "📋 全部",
        addCategory: "添加分类",
        newCategory: "新建分类",
        editCategory: "编辑分类",
        categoryName: "分类名称",
        categoryColor: "颜色",
        uncategorized: "未分类",
        unknownCategory: "未知分类",
        showMoreCategories: "展示更多",
        showMoreTags: "展开更多",
        showLessTags: "展开更少",

        // 联系作者
        contactAuthor: "联系作者",
        
        // 搜索和筛选
        searchTitle: "支持通过【#标签(空格)】、【>父任务全称】或【@截止日期(如 2026-09-19)】进行特殊搜索",
        searchClear: "清空搜索",
        searchClearKeyword: "清除搜索文本",
        searchClearDueDate: "清除截止时间筛选",
        searchClearTags: "清除标签筛选",
        searchDuePrefix: "截止",
        searchDueDate: "按截止时间搜索（也可直接输入 @2026-09-19）",
        filterPriority: "所有优先级",
        filterStatus: "所有状态",
        
        // 日期筛选选项
        dueDateAll: "所有时间",
        dueDateToday: "今天",
        dueDateTomorrow: "明天", 
        dueDateWeek: "本周内",
        dueDateMonth: "本月内",
        dueDateNoDueDate: "无截止日期",
        
        // 视图切换
        listView: "列表视图",
        calendarView: "日历视图",
        timelineView: "时间轴视图",
        statsView: "统计视图",
        viewSwitched: "视图已切换",
        viewToggleTip: "切换视图，日历视图不显示无截止日期数据",

        // 任务导入导出
        exportTasks: "导出任务",

        // 导出任务弹窗
        exportExcel: "导出Excel",
        exportStatusLabel: "完成状态",
        exportDueYear: "截止年份",
        exportAllYears: "全部年份",
        exportDueMonth: "截止月份",
        exportAllMonths: "全部月份",
        allCategoriesOption: "全部分类",
        // 下拉里"全部"与优先级的短形式（区别于列表徽章用的"高优先级"等完整说法）
        all: "全部",
        priorityShortHigh: "高",
        priorityShortMedium: "中",
        priorityShortLow: "低",
        month1: "1月",
        month2: "2月",
        month3: "3月",
        month4: "4月",
        month5: "5月",
        month6: "6月",
        month7: "7月",
        month8: "8月",
        month9: "9月",
        month10: "10月",
        month11: "11月",
        month12: "12月",

        // 联系作者二维码弹窗
        qrCodeCaption: "扫描二维码联系作者",
        contactAuthorQrAlt: "联系作者二维码",

        // 日历相关
        // 日历表头星期名：HTML 上逐日静态标注，一个 key 对应一天
        calendarWeekdaySun: "日",
        calendarWeekdayMon: "一",
        calendarWeekdayTue: "二",
        calendarWeekdayWed: "三",
        calendarWeekdayThu: "四",
        calendarWeekdayFri: "五",
        calendarWeekdaySat: "六",
        // 日期选择器（Pikaday）文案：按整份 i18n 配置给出，新增语言时无需改动 JS
        calendarPrevMonth: "上个月",
        calendarNextMonth: "下个月",
        calendarMonths: ["一月", "二月", "三月", "四月", "五月", "六月",
            "七月", "八月", "九月", "十月", "十一月", "十二月"],
        calendarWeekdaysFull: ["星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"],
        calendarWeekdaysShort: ["日", "一", "二", "三", "四", "五", "六"],

        // 任务表头
        taskHeaderName: "任务名称",
        taskHeaderPriority: "优先级",
        taskHeaderDueDate: "到期时间",
        taskHeaderTag: "标签",
        taskHeaderAction: "操作",
        taskHeaderCategory: "所属分类",
        taskHeaderParentTask: "关联父项任务",
        taskHeaderAttachments: "任务附件",
        taskHeaderCreatedAt: "创建时间",
        taskHeaderUpdatedAt: "更新时间",

        // 任务列表显示列配置
        columnConfigTitle: "配置显示列",
        columnConfigTip: "配置列表查看列",
        columnConfigDesc: "勾选需要在任务列表中展示的列",
        columnConfigLocked: "必选",
        columnConfigReset: "恢复默认",
        columnConfigSaved: "显示列配置已保存",
        columnConfigSaveFailed: "显示列配置保存失败",
        columnConfigMinTip: "至少需要保留一列",
        
        // 任务列表操作项提示语
        recurringTaskEditTip: "周期性任务不支持编辑",
        normalTaskEditTip: "编辑",
        taskViewTip: "查看",
        taskDeleteTip: "删除",
        taskCopyTip: "复制任务",

        // 分页
        paginationShowing: "显示",
        paginationOf: "共",
        paginationItems: "条",
        // 每页条数选项：数值由 data-i18n-prefix 留在 HTML 上
        paginationPerPage: "条/页",
        paginationFirst: "首页",
        paginationPrev: "上一页", 
        paginationNext: "下一页",
        paginationLast: "末页",
        
        // 空状态
        emptyTasks: "暂无任务",
        emptyTasksMessage: "点击\"新建任务\"按钮创建你的第一个任务",

        // 时间轴视图工具栏
        timelinePrevWeek: "上一周",
        timelineNextWeek: "下一周",
        timelineDecreaseWeeks: "减少显示周数",
        timelineIncreaseWeeks: "增加显示周数",
        timelineWeekMinus: "-1周",
        timelineWeekPlus: "+1周",
        timelineWeekCount: "{count}周 / 最多4周",
        timelineDays: "{count}天",

        // 统计视图工具栏
        statsBasis: "统计口径",
        statsBasisCreated: "创建时间",
        statsBasisDue: "截止时间",
        statsBasisCompleted: "完成时间（仅已完成）",
        statsScope: "时间范围",
        statsScopeAll: "全部时间",
        statsScopeYear: "按年份",
        statsScopeMonth: "按月份",
        statsScopeWeek: "按周",
        statsYear: "年份",
        statsMonth: "月份",
        statsWeek: "周",
        
        // 操作提示
        taskCreated: "任务创建成功",
        taskUpdated: "任务更新成功", 
        taskDeleted: "任务删除成功",
        taskCompleted: "任务已完成",
        taskReopened: "任务已重新开启",
        taskCreatedButFiltered: "任务已创建，但不在当前筛选结果中",
        loadingTaskFailed: "加载任务失败",
        periodicTaskEditFailed: "周期性任务不支持编辑，请删除后重新创建",
        periodicTaskCopyFailed: "周期性任务不支持复制",
        taskCopied: "已复制任务信息，确认后即可保存为新任务",
        periodicTaskDeleted: "整个周期任务删除成功",
        operationFailed: "操作失败",
        taskTagDeleted: "标签删除成功",
        errorTagNameRequired: "请输入标签名",
        errorTagExisted: "标签已存在",
        windowOnTopSet: "窗口已设置置顶",
        windowOnTopUnset: "窗口已取消置顶",
        languageSwitchFailed: "语言切换失败",
        languageSwitchTo: "已切换到",
        initializationFailed: "应用初始化失败",
        unknownErrorOccurred: "发生了未知错误",
        refreshDataFailed: "刷新数据失败",
        calendarPermissionRequired: "未获得日历权限，请在系统设置中开启后，到期提醒才能写入系统日历",
        resetStateFailed: "应用状态重置失败",
        resetStateSuccess: "应用状态已重置",
        sharingStopped: "共享已停止",
        sharingStarted: "共享已启动",
        noDeviceFound: "未找到可用的设备",
        receiveDataFailed: "接收数据失败",
        dataImportedSuccess: "数据导入成功",
        dataImportedFailed: "数据导入失败",
        transferIncludeAttachments: "同时传输附件文件（体积较大，耗时更久）",
        attachmentRecords: "附件记录数",
        attachmentFiles: "附件文件数",
        loadCategoriesFailed: "加载分类失败",
        errorCategoryNameRequired: "请输入分类名称",
        errorCategoryExisted: "分类名称已存在",
        categoryCreated: "分类创建成功",
        categoryUpdated: "分类更新成功",
        categoryDeleted: "分类删除成功",
        showTaskFor: "当前任务日期：",

        // 错误消息
        errorTitleRequired: "请输入任务标题",
        errorInvalidDateTime: "截止时间不能早于当前时间",
        errorDateTimeIncomplete: "日期和时间选择不完整",
        errorRecurrenceTypeRequired: "请选择重复周期",
        errorRecurrenceCountRequired: "请输入有效的循环次数",
        errorRecurrenceCronRequired: "请输入 Cron 表达式",
        errorRecurrenceTimesRequired: "请至少添加一个提醒时间点",
        errorRecurrenceTimesLimit: "提醒时间点数量已达上限",
        errorRecurrenceWeekdaysRequired: "请至少选择一个星期",
        errorRecurrenceMonthDaysRequired: "请至少选择一个日期",
        errorRecurrenceYearlyRequired: "请选择有效的月份和日期",
        errorRecurrenceIntervalRequired: "请填写完整的时间段",
        errorRecurrenceIntervalOrder: "时间段结束时间需晚于开始时间",
        errorRecurrenceIntervalMinutes: "间隔分钟需在 1-1440 之间",
        errorRecurrenceEndDateRequired: "请选择有效的结束日期",

        // 周期性任务
        recurringTask: "周期性任务",
        recurrenceType: "重复周期",
        recurrenceCount: "循环次数*",
        recurrenceDaily: "每天",
        recurrenceWeekly: "每周",
        recurrenceMonthly: "每月",
        recurrenceYearly: "每年",
        recurrenceCountRequired: "循环次数不能为空",
        recurrenceChoose: "请选择",
        recurringEditNotice: "非周期性任务编辑模式下不支持改周期性任务",
        // 时间设置：单次任务 / 周期性任务
        scheduleMode: "时间设置",
        scheduleModeOnce: "单次任务",
        scheduleModeRecurring: "周期性任务",
        timeLabel: "时间",
        // 配置模式
        recurrenceMode: "配置模式",
        recurrenceModeNormal: "普通模式",
        recurrenceModeCron: "Cron 模式",
        // 每天
        recurrenceDailyMode: "提醒方式",
        recurrenceDailyModeTimes: "指定时间点",
        recurrenceDailyModeInterval: "时间段 + 间隔",
        recurrenceIntervalMinutes: "间隔（分钟）",
        // 提醒时间点
        recurrenceTimes: "提醒时间点",
        recurrenceAddTime: "添加时间点",
        // 每周 / 每月 / 每年
        recurrenceWeeklyDays: "选择星期（可多选）",
        recurrenceMonthlyDays: "选择日期（可多选）",
        recurrenceMonthlyDaysHint: "不存在的日期（如 2 月 30 日）会自动跳过",
        recurrenceYearlyMonth: "月份",
        recurrenceYearlyDay: "日期",
        recurrenceLastDay: "最后一天",
        recurrenceMonthUnit: "{month}月",
        recurrenceDayUnit: "{day}日",
        recurrenceWeekdays: ["周一", "周二", "周三", "周四", "周五", "周六", "周日"],
        // Cron
        recurrenceCron: "Cron 表达式",
        recurrenceCronHint: "格式：分 时 日 月 周（如 0 9 * * 1-5 表示工作日 09:00；*/30 9-18 * * * 表示 09:00–18:00 每 30 分钟）",
        // 结束条件
        recurrenceEndType: "结束方式",
        recurrenceEndByCount: "按次数结束",
        recurrenceEndByDate: "按日期结束",
        recurrenceEndHabit: "习惯",
        recurrenceHabitHint: "每次只保留一条待办，完成后才按周期生成下一条",
        recurrenceEndDate: "结束日期",
        // 周期基本配置小标题
        recurrenceTypeLabel: "重复周期",
        dailyIntervalLabel: "时间段与间隔",
        recurrenceIntervalStartShort: "开始",
        recurrenceIntervalEndShort: "结束",
        recurrenceYearlyLabel: "每年日期",
        recurrenceCountLabel: "循环次数",
        recurrenceWeeklyDaysHint: "可多选，不选则不会提醒",
        // 预览
        recurrencePreviewBtn: "预览提醒时间",
        recurrencePreviewTitle: "接下来 10 次提醒：",
        recurrencePreviewHabitTitle: "首次提醒时间：",
        recurrencePreviewEmpty: "当前规则没有匹配到提醒时间，请调整配置",

        // 设置中心
        settingsWindow: "通用设置",
        settingsWindowTop: "窗口置顶",
        settingsAutoStart: "开机启动",
        settingsShortcut: "快捷操作",
        settingsApply: "应用",
        settingsData: "数据管理",
        settingsDataShare: "共享数据",
        settingsDataSync: "同步数据",
        // 自定义主题配色
        settingsThemeColors: "主题配色",
        settingsThemeMode: "主题模式",
        settingsThemeModeDefault: "默认模式",
        settingsThemeModeDark: "深色模式",
        settingsThemeModeCustom: "自定义模式",
        settingsThemeModeSwitched: "主题已切换为",
        settingsThemeLockedHint: "切换到「自定义模式」后可编辑以下配色",
        settingsThemeBaseLight: "浅色",
        settingsThemeBaseDark: "深色",
        settingsThemePreset: "预设色板",
        settingsThemeLinkPriority: "优先级跟随语义色",
        settingsThemeReset: "恢复默认",
        settingsThemeSave: "保存配色",
        settingsThemeSaved: "配色已保存",
        settingsThemeInvalid: "存在非法颜色值（应为 #RRGGBB）",
        settingsThemeContrastHint: "对比度偏低，文字自动加深",
        themeColorPrimary: "主体颜色",
        themeColorSuccess: "成功颜色",
        themeColorWarning: "警告颜色",
        themeColorDanger: "危险颜色",
        themeColorInfo: "信息颜色",
        themeColorPriorityHigh: "高优先级",
        themeColorPriorityMedium: "中优先级",
        themeColorPriorityLow: "低优先级",
        themeColorPriorityNone: "无优先级",
        settingsSuccess: "设置成功",
        settingsSaveSuccess: "保存成功",
        settingsFailed: "设置失败",
        settingsShortcutAs: "已设置为",
        settingsShortcutNeedRestart: "请重启应用后尝试",
        settingsShortcutEnabled: "快捷操作已启用",
        settingsShortcutDisabled: "快捷操作已禁用",
        settingsAutoStartEnabled: "开机启动已启用",
        settingsAutoStartDisabled: "开机启动已禁用",
        settingsAutoStartWarning: "当前平台不支持开机启动功能",
        settingsConnectSuccess: "连接成功！可以正常使用云端同步功能！",
        settingsConnectionFailed: "连接失败",
        settingsImportWarning: "注意：当前操作将覆盖本地所有数据。建议先备份重要数据。是否继续？",
        settingsStorageWarning: "注意：这将影响所有数据的读写操作，当前数据会被复制到新的存储目录，原目录的数据文件将保留为备份。建议先备份重要数据。是否继续？",
        settingsStorageUnchanged: "存储目录未变更，已重新加载数据。",
        settingsSyncModeLocalWarning: "注意：当前操作将直接触发一次本地数据强制覆盖远程文件数据。建议先备份重要数据。是否继续？",
        settingsSyncModeRemoteWarning: "注意：当前操作将直接触发一次远程数据强制覆盖本地文件数据。建议先备份重要数据。是否继续？",
        settingsSyncCloseWarning: "注意：当前操作将导致无法同步云端数据，是否继续？",
        storageBackupKept: "旧数据仍保留在原目录：",
        storageBackupCleanupConfirm: "是否清理原目录中保留的旧数据备份？清理后新目录的数据不受影响；若清理后原目录已空，会一并移除该空目录。",
        settingsStorageLargeWarning: "注意：本次需要复制约 {size} 数据（附件 {count} 个），耗时可能较长，期间请勿关闭应用。",
        storageMigrationTitle: "正在切换存储目录",
        storageMigrationPreparing: "正在准备迁移…",
        storageMigrationDatabase: "正在复制数据文件…",
        storageMigrationAttachments: "正在复制附件",
        storageMigrationWorking: "正在迁移数据…",
        storageMigrationProgressLost: "迁移进度查询失败，请检查应用状态",
        storageMigrationCancel: "取消",
        storageMigrationCancelling: "正在取消…",
        storageMigrationCancelFailed: "取消失败，请稍后重试",
        storageMigrationCancelled: "已取消切换，数据仍在原存储目录",

        // 语言设置
        language: "语言切换",

        // 关于
        about: "关于",
        sourceCode: "源码地址",
        document: "相关文档",
        documentText: "TodoList功能介绍",
        statement: "开源声明",
        statementText: "仅供使用，勿商用",

        // 数据存储路径
        dataStoragePath: "存储目录",

        // 确认对话框
        
        // 周期性任务删除选项
        
        // 更多选项
        moreOptions: "更多选项",

        // 小屏更多菜单的快捷筛选项
        moreMenuFilterAll: "显示所有任务",
        moreMenuFilterUncompleted: "显示未完成任务",
        moreMenuFilterOverdue: "显示已逾期任务",
        moreMenuFilterToday: "仅显示今天任务",
        moreMenuFilterTag: "显示含标签任务",
        moreMenuPrevMonthTasks: "上一个月任务",
        moreMenuNextMonthTasks: "下一个月任务",
        optional: "可选",
        required: "必填",

        // 父任务选择器
        parentTask: "父任务",
        parentTaskPlaceholder: "点击选择或输入搜索未完成的任务",
        loadMore: "加载更多",
        noMatchingTasks: "无匹配任务",

        // 日期时间字段的清除按钮
        clearDate: "清空日期",
        clearTime: "清空时间",
        clearEndDate: "清空结束日期",
        
        // 数据传输
        dataTransfer: "数据传输",
        shareMode: "共享数据",
        receiveMode: "接收数据",
        currentDataSummary: "当前数据摘要",
        shareSettings: "共享设置",
        shareFirewallNotice: "⚠️ 开启/停止共享涉及配置防火墙，需要管理员权限",
        startShare: "启动共享",
        stopShare: "停止共享",
        shareStatus: "共享状态",
        ipAddress: "IP地址：",
        port: "端口：",
        sharingData: "正在共享数据",
        scanDevice: "扫描设备",
        scanNetworkDevice: "扫描局域网设备",
        availableDevices: "可用设备",
        noDevicesFound: "未找到设备",
        receivedDataPreview: "接收到的数据预览",
        waitingForData: "等待接收数据...",
        importWarning: "⚠️ 注意: 导入数据将覆盖当前所有数据，建议先备份数据！",
        confirmImport: "确认导入",
        cancelImport: "取消",

        // 数据同步
        dataSync: "数据云同步",
        syncType: "同步类型",
        syncTypeJianguoyun: "坚果云",
        syncTypeCustom: "自定义",
        url: "地址*",
        account: "账号*",
        password: "密码*",
        filepath: "路径*",
        firstSyncMode: "首次同步",
        firstSyncModeRemote: "远程覆盖本地",
        firstSyncModeLocal: "本地覆盖远程",
        webdavUrlPlaceholder: "请输入WebDAV服务器地址",
        webdavAccountPlaceholder: "请输入邮箱地址",
        webdavPasswordPlaceholder: "请输入授权应用密码",
        webdavPathPlaceholder: "请输入远程同步目录，如 /todolist",
        testConnection: "测试连接",
        saveConfiguration: "保存配置",
        autoSyncNotice: "⚠️ 如云路径和本地数据存储路径存在映射关系，请勿开启云同步，避免重复更新数据；首次同步外的数据自动同步规则：存在数据更新的端点，15s内会自动同步数据到其他端点",
    },
    
    // 英文
    en: {
        // 应用标题和基本界面
        appTitle: "📝 Todo List",
        settingsBtn: "Settings",
        settings: "Settings",
        save: "Save",
        cancel: "Cancel",
        confirm: "Confirm",
        delete: "Delete",
        edit: "Edit",
        view: "View",
        close: "Close",
        loading: "Loading...",
        itemRequired: "Please fill in the required fields.",
        
        // 任务相关
        task: "Task",
        tasks: "Tasks",
        newTask: "New Task",
        editTask: "Edit Task",
        copyTask: "Copy Task",
        taskTitle: "Task Title",
        taskDescription: "Task Description",
        taskPriority: "Priority",
        taskCategory: "Category",
        taskDueDate: "Due Date",
        taskCreateTime: "Created",
        taskUpdateTime: "Updated",
        taskTags: "Tags",
        taskTag: "Tag",
        taskTagsHint: "(select or add tags)",
        taskStatus: "Status",

        // 任务详情
        noTaskTags: "No tags",
        noTaskDescription: "No description",

        // 任务附件
        taskAttachments: "Attachments",
        noTaskAttachments: "No attachments",
        attachment: "Attachment",
        attachmentEmpty: "No attachments",
        attachmentUploadFile: "Upload File",
        attachmentAddLink: "Add Link",
        attachmentAddFolder: "Link Folder",
        folderAddUnsupportedOnMobile: "Linking folders is not supported on mobile",
        folderOpenUnsupportedOnMobile: "Opening task folders is not supported on mobile",
        folderOpenFailed: "Failed to open the folder. It may have been moved or deleted",
        attachmentMaxReached: "You can add at most {count} attachments",
        attachmentTooLarge: "Each attachment cannot exceed 10MB, {count} file(s) ignored",
        attachmentLinkRequired: "Please enter the link URL",
        attachmentLinkInvalid: "Invalid link URL",
        attachmentOpenFailed: "Failed to open attachment",
        attachmentOpenFallback: "Unable to open the attachment directly. Its folder has been opened, please open the file manually.",
        attachmentRevealFailed: "Failed to open the containing folder",
        attachmentOptionalHint: "(optional, max 5, each within 10MB)",
        attachmentAddLinkTitle: "Add Link",
        attachmentLinkName: "Link Name",
        attachmentLinkNameHint: "(optional, defaults to the URL)",
        attachmentLinkNamePlaceholder: "Please enter the link name",
        attachmentLinkUrl: "Link URL",
        attachmentAdd: "Add",

        // 优先级
        priorityHigh: "High Priority",
        priorityMedium: "Medium Priority",
        priorityLow: "Low Priority", 
        priorityNone: "No Priority",
        // 优先级-图标
        high: "High",
        medium: "Medium",
        low: "Low",
        none: "None",
        
        // 状态
        statusCompleted: "Completed",
        statusUncompleted: "Uncompleted",
        statusPending: "Pending (Not Overdue)",
        statusOverdue: "Overdue",
        
        // 统计信息
        statsTotalTasks: "Total Tasks",
        statsCompletedTasks: "Completed",
        statsUnCompletedTasks: "Uncompleted",
        statsCompletionRate: "Completion Rate",
        statsLastUpdateTime: "Last Updated",
        statsTodayCompletedTasks: "Completed Today",
        statsOverDueDateTasks: "Overdue",
        statsCategories: "Total Categories",
        statsAllTime: "All Time",
        
        // 分类管理
        categories: "Categories",
        allCategories: "📋 All",
        addCategory: "Add Category",
        newCategory: "New Category",
        editCategory: "Edit Category",
        categoryName: "Category Name",
        categoryColor: "Color",
        uncategorized: "Uncategorized",
        unknownCategory: "Unknown Category",
        showMoreCategories: "More",
        showMoreTags: "More",
        showLessTags: "Less",

        // 联系作者
        contactAuthor: "Contact Author",
        
        // 搜索和筛选
        searchTitle: "Supports #tag(space), >parent-task or @due-date(e.g. 2026-09-19) search",
        searchClear: "Clear Search",
        searchClearKeyword: "Clear search text",
        searchClearDueDate: "Clear due date filter",
        searchClearTags: "Clear tag filter",
        searchDuePrefix: "Due",
        searchDueDate: "Search by due date (or type @2026-09-19)",
        filterPriority: "All Priorities",
        filterStatus: "All Statuses",
        
        // 日期筛选选项
        dueDateAll: "All Time",
        dueDateToday: "Today",
        dueDateTomorrow: "Tomorrow",
        dueDateWeek: "This Week",
        dueDateMonth: "This Month",
        dueDateNoDueDate: "No Due Date",
        
        // 视图切换
        listView: "List View",
        calendarView: "Calendar View",
        timelineView: "Timeline View",
        statsView: "Stats View",
        viewSwitched: "View switched",
        viewToggleTip: "Switch view; tasks without a due date are hidden in calendar view",

        // 任务导入导出
        exportTasks: "Export Tasks",

        // 导出任务弹窗
        exportExcel: "Export Excel",
        exportStatusLabel: "Completion Status",
        exportDueYear: "Due Year",
        exportAllYears: "All Years",
        exportDueMonth: "Due Month",
        exportAllMonths: "All Months",
        allCategoriesOption: "All Categories",
        // 下拉里"全部"与优先级的短形式（区别于列表徽章用的"高优先级"等完整说法）
        all: "All",
        priorityShortHigh: "High",
        priorityShortMedium: "Medium",
        priorityShortLow: "Low",
        month1: "Jan",
        month2: "Feb",
        month3: "Mar",
        month4: "Apr",
        month5: "May",
        month6: "Jun",
        month7: "Jul",
        month8: "Aug",
        month9: "Sep",
        month10: "Oct",
        month11: "Nov",
        month12: "Dec",

        // 联系作者二维码弹窗
        qrCodeCaption: "Scan the QR code to contact the author",
        contactAuthorQrAlt: "QR code to contact the author",
        
        // 日历相关
        // 日历表头星期名：HTML 上逐日静态标注，一个 key 对应一天
        calendarWeekdaySun: "Sun",
        calendarWeekdayMon: "Mon",
        calendarWeekdayTue: "Tue",
        calendarWeekdayWed: "Wed",
        calendarWeekdayThu: "Thu",
        calendarWeekdayFri: "Fri",
        calendarWeekdaySat: "Sat",
        // 日期选择器（Pikaday）文案：按整份 i18n 配置给出，新增语言时无需改动 JS
        calendarPrevMonth: "Prev",
        calendarNextMonth: "Next",
        calendarMonths: ["January", "February", "March", "April", "May", "June",
            "July", "August", "September", "October", "November", "December"],
        calendarWeekdaysFull: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        calendarWeekdaysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],

        // 任务表头
        taskHeaderName: "Task Name",
        taskHeaderPriority: "Priority",
        taskHeaderDueDate: "Due Date",
        taskHeaderTag: "Tag",
        taskHeaderAction: "Action",
        taskHeaderCategory: "Category",
        taskHeaderParentTask: "Parent Task",
        taskHeaderAttachments: "Attachments",
        taskHeaderCreatedAt: "Created",
        taskHeaderUpdatedAt: "Updated",

        // 任务列表显示列配置
        columnConfigTitle: "Configure Columns",
        columnConfigTip: "Configure list columns",
        columnConfigDesc: "Select the columns to display in the task list",
        columnConfigLocked: "Required",
        columnConfigReset: "Reset to Default",
        columnConfigSaved: "Column settings saved",
        columnConfigSaveFailed: "Failed to save column settings",
        columnConfigMinTip: "At least one column is required",
        
        // 任务列表操作项提示语
        recurringTaskEditTip: "Periodic tasks cannot be edited",
        normalTaskEditTip: "Edit",
        taskViewTip: "View",
        taskDeleteTip: "Delete",
        taskCopyTip: "Copy Task",

        // 分页
        paginationShowing: "Showing",
        paginationOf: "of",
        paginationItems: "items",
        // 每页条数选项：数值由 data-i18n-prefix 留在 HTML 上
        paginationPerPage: "items/page",
        paginationFirst: "First",
        paginationPrev: "Previous",
        paginationNext: "Next",
        paginationLast: "Last",
        
        // 空状态
        emptyTasks: "No Tasks",
        emptyTasksMessage: "Click the \"New Task\" button to create your first task",

        // 时间轴视图工具栏
        timelinePrevWeek: "Previous week",
        timelineNextWeek: "Next week",
        timelineDecreaseWeeks: "Show one week less",
        timelineIncreaseWeeks: "Show one week more",
        timelineWeekMinus: "-1 week",
        timelineWeekPlus: "+1 week",
        timelineWeekCount: "{count} weeks / 4 weeks max",
        timelineDays: "{count} days",

        // 统计视图工具栏
        statsBasis: "Basis",
        statsBasisCreated: "Created",
        statsBasisDue: "Due date",
        statsBasisCompleted: "Completion time (completed only)",
        statsScope: "Time Range",
        statsScopeAll: "All Time",
        statsScopeYear: "By year",
        statsScopeMonth: "By month",
        statsScopeWeek: "By week",
        statsYear: "Year",
        statsMonth: "Month",
        statsWeek: "Week",
        
        // 操作提示
        taskCreated: "Task created successfully",
        taskUpdated: "Task updated successfully",
        taskDeleted: "Task deleted successfully",
        taskCompleted: "Task completed",
        taskReopened: "Task reopened",
        taskCreatedButFiltered: "Task created, but not shown in the current filter results",
        loadingTaskFailed: "Failed to load tasks",
        periodicTaskEditFailed: "Periodic tasks cannot be edited, please delete and recreate them",
        periodicTaskCopyFailed: "Periodic tasks cannot be copied",
        taskCopied: "Task info copied. Confirm to save it as a new task",
        periodicTaskDeleted: "The entire recurring series has been deleted",
        operationFailed: "Operation failed",
        taskTagDeleted: "The tag has been deleted successfully",
        errorTagNameRequired: "Please enter a tag name",
        errorTagExisted: "The tag already exists",
        windowOnTopSet: "Window set to stay on top",
        windowOnTopUnset: "Window no longer stays on top",
        languageSwitchFailed: "Language switch failed",
        languageSwitchTo: "Switched to ",
        initializationFailed: "Application initialization failed",
        unknownErrorOccurred: "An unknown error occurred",
        refreshDataFailed: "Failed to refresh data",
        calendarPermissionRequired: "Calendar permission not granted. Enable it in system settings so due reminders can be written to the system calendar",
        resetStateFailed: "Failed to reset application state",
        resetStateSuccess: "Application state has been reset",
        sharingStopped: "Sharing stopped",
        sharingStarted: "Sharing started",
        noDeviceFound: "No available devices found",
        receiveDataFailed: "Failed to receive data",
        dataImportedSuccess: "Data imported successfully",
        dataImportedFailed: "Data import failed",
        transferIncludeAttachments: "Also transfer attachment files (large, may take longer)",
        attachmentRecords: "Attachment records",
        attachmentFiles: "Attachment files",
        loadCategoriesFailed: "Failed to load categories",
        errorCategoryNameRequired: "Please enter a category name",
        errorCategoryExisted: "Category name already exists",
        categoryCreated: "Category created successfully",
        categoryUpdated: "Category updated successfully",
        categoryDeleted: "Category deleted successfully",
        showTaskFor: "Show tasks for ",

        // 错误消息
        errorTitleRequired: "Please enter task title",
        errorInvalidDateTime: "Due time cannot be earlier than current time",
        errorDateTimeIncomplete: "Date and time must be selected together",
        errorRecurrenceTypeRequired: "Please select recurrence type",
        errorRecurrenceCountRequired: "Please enter valid repeat count",
        errorRecurrenceCronRequired: "Please enter a cron expression",
        errorRecurrenceTimesRequired: "Please add at least one reminder time",
        errorRecurrenceTimesLimit: "The number of reminder times has reached the limit",
        errorRecurrenceWeekdaysRequired: "Please select at least one weekday",
        errorRecurrenceMonthDaysRequired: "Please select at least one day of month",
        errorRecurrenceYearlyRequired: "Please select a valid month and day",
        errorRecurrenceIntervalRequired: "Please fill in the complete time range",
        errorRecurrenceIntervalOrder: "The end time must be later than the start time",
        errorRecurrenceIntervalMinutes: "The interval must be between 1 and 1440 minutes",
        errorRecurrenceEndDateRequired: "Please select a valid end date",

        // 周期性任务
        recurringTask: "Recurring Task",
        recurrenceType: "Recurrence",
        recurrenceCount: "Repeat Count",
        recurrenceDaily: "Daily",
        recurrenceWeekly: "Weekly",
        recurrenceMonthly: "Monthly",
        recurrenceYearly: "Yearly",
        recurrenceCountRequired: "Repeat count cannot be empty",
        recurrenceChoose: "Please select",
        recurringEditNotice: "Cannot convert to a recurring task while editing a non-recurring task",
        // 时间设置：单次任务 / 周期性任务
        scheduleMode: "Schedule",
        scheduleModeOnce: "One-time",
        scheduleModeRecurring: "Recurring",
        timeLabel: "Time",
        // 配置模式
        recurrenceMode: "Mode",
        recurrenceModeNormal: "Standard",
        recurrenceModeCron: "Cron",
        // 每天
        recurrenceDailyMode: "Reminder Type",
        recurrenceDailyModeTimes: "Fixed Times",
        recurrenceDailyModeInterval: "Range + Interval",
        recurrenceIntervalMinutes: "Interval (minutes)",
        // 提醒时间点
        recurrenceTimes: "Reminder Times",
        recurrenceAddTime: "Add Time",
        // 每周 / 每月 / 每年
        recurrenceWeeklyDays: "Select weekdays",
        recurrenceMonthlyDays: "Select days of month",
        recurrenceMonthlyDaysHint: "Non-existent dates (e.g. Feb 30) are skipped automatically",
        recurrenceYearlyMonth: "Month",
        recurrenceYearlyDay: "Day",
        recurrenceLastDay: "Last Day",
        recurrenceMonthUnit: "Month {month}",
        recurrenceDayUnit: "Day {day}",
        recurrenceWeekdays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
        // Cron
        recurrenceCron: "Cron Expression",
        recurrenceCronHint: "Format: minute hour day month weekday (e.g. 0 9 * * 1-5 = weekdays 09:00; */30 9-18 * * * = every 30 min from 09:00 to 18:00)",
        // 结束条件
        recurrenceEndType: "Ends",
        recurrenceEndByCount: "After N times",
        recurrenceEndByDate: "On a date",
        recurrenceEndHabit: "Habit",
        recurrenceHabitHint: "Keeps only one pending task; the next one is created after you complete it",
        recurrenceEndDate: "End Date",
        // 周期基本配置小标题
        recurrenceTypeLabel: "Repeat",
        dailyIntervalLabel: "Range & Interval",
        recurrenceIntervalStartShort: "Start",
        recurrenceIntervalEndShort: "End",
        recurrenceYearlyLabel: "Date",
        recurrenceCountLabel: "Times",
        recurrenceWeeklyDaysHint: "Multiple selection allowed; nothing is reminded if empty",
        // 预览
        recurrencePreviewBtn: "Preview Reminders",
        recurrencePreviewTitle: "Next 10 reminders:",
        recurrencePreviewHabitTitle: "First reminder:",
        recurrencePreviewEmpty: "No reminders match the current rule. Please adjust it",

        // 设置中心
        settingsWindow: "General Settings",
        settingsWindowTop: "Window Always On Top",
        settingsAutoStart: "Start on Boot",
        settingsShortcut: "Shortcut",
        settingsApply: "Apply",
        settingsData: "Data Management",
        settingsDataShare: "Share Data",
        settingsDataSync: "Sync Data",
        // Custom theme colors
        settingsThemeColors: "Theme Colors",
        settingsThemeMode: "Theme Mode",
        settingsThemeModeDefault: "Default",
        settingsThemeModeDark: "Dark",
        settingsThemeModeCustom: "Custom",
        settingsThemeModeSwitched: "Theme switched to ",
        settingsThemeLockedHint: "Switch to \"Custom\" to edit the colors below",
        settingsThemeBaseLight: "Light",
        settingsThemeBaseDark: "Dark",
        settingsThemePreset: "Presets",
        settingsThemeLinkPriority: "Priority follows semantic colors",
        settingsThemeReset: "Reset to Default",
        settingsThemeSave: "Save Colors",
        settingsThemeSaved: "Color scheme saved",
        settingsThemeInvalid: "Invalid color value (expected #RRGGBB)",
        settingsThemeContrastHint: "Low contrast; button text will switch to dark automatically",
        themeColorPrimary: "Primary",
        themeColorSuccess: "Success",
        themeColorWarning: "Warning",
        themeColorDanger: "Danger",
        themeColorInfo: "Info",
        themeColorPriorityHigh: "High priority",
        themeColorPriorityMedium: "Medium priority",
        themeColorPriorityLow: "Low priority",
        themeColorPriorityNone: "No priority",
        settingsSuccess: "Settings saved",
        settingsSaveSuccess: "Saved successfully",
        settingsFailed: "Failed to save settings",
        settingsShortcutAs: "Hotkey set to ",
        settingsShortcutNeedRestart: "Please restart the app to apply changes.",
        settingsShortcutEnabled: "Shortcut enabled",
        settingsShortcutDisabled: "Shortcut disabled",
        settingsAutoStartEnabled: "Auto-start on boot is enabled.",
        settingsAutoStartDisabled: "Auto-start on boot is disabled.",
        settingsAutoStartWarning: "The current platform does not support the auto-start on boot feature.",
        settingsConnectSuccess: "Connected! Cloud sync is ready to use.",
        settingsConnectionFailed: "Connection failed",
        settingsImportWarning: "Note: This will overwrite all local data. We recommend backing up important data first. Continue?",
        settingsStorageWarning: "Note: This affects all data read and write operations. Your data will be copied to the new storage directory, and the original file will be kept as a backup. We recommend backing up important data first. Continue?",
        settingsStorageUnchanged: "Storage directory unchanged, data reloaded.",
        settingsSyncModeLocalWarning: "Warning: This will immediately overwrite the remote file with your local data. We recommend backing up important data first. Continue?",
        settingsSyncModeRemoteWarning: "Warning: This will immediately overwrite your local data with the remote file. We recommend backing up important data first. Continue?",
        settingsSyncCloseWarning: "Warning: This will disable cloud sync. Continue?",
        storageBackupKept: "The old data is still kept in the original directory: ",
        storageBackupCleanupConfirm: "Do you want to remove the old data backup kept in the original directory? Data in the new directory will not be affected. If the original directory becomes empty, it will be removed as well.",
        settingsStorageLargeWarning: "Note: About {size} of data ({count} attachments) will be copied. This may take a while, so please keep the app open.",
        storageMigrationTitle: "Switching storage directory",
        storageMigrationPreparing: "Preparing migration...",
        storageMigrationDatabase: "Copying database file...",
        storageMigrationAttachments: "Copying attachments",
        storageMigrationWorking: "Migrating data...",
        storageMigrationProgressLost: "Failed to read migration progress. Please check the app status",
        storageMigrationCancel: "Cancel",
        storageMigrationCancelling: "Cancelling...",
        storageMigrationCancelFailed: "Failed to cancel. Please try again later",
        storageMigrationCancelled: "Switch cancelled. Data remains in the original directory",

        // 语言设置
        language: "Language",

        // 关于
        about: "About",
        sourceCode: "Source Code",
        document: "Documentation",
        documentText: "Usage Guide",
        statement: "License",
        statementText: "Personal use only, not for commercial use.",

        // 数据存储路径
        dataStoragePath: "Storage Directory",

        // 确认对话框
        
        // 周期性任务删除选项
        
        // 更多选项
        moreOptions: "More Options",

        // 小屏更多菜单的快捷筛选项
        moreMenuFilterAll: "Show All Tasks",
        moreMenuFilterUncompleted: "Show Uncompleted Tasks",
        moreMenuFilterOverdue: "Show Overdue Tasks",
        moreMenuFilterToday: "Show Today's Tasks Only",
        moreMenuFilterTag: "Show Tagged Tasks",
        moreMenuPrevMonthTasks: "Previous Month's Tasks",
        moreMenuNextMonthTasks: "Next Month's Tasks",
        optional: "Optional",
        parentTask: "Parent Task",
        parentTaskPlaceholder: "Click to select or search uncompleted tasks",
        loadMore: "Load More",
        noMatchingTasks: "No matching tasks",
        clearDate: "Clear date",
        clearTime: "Clear time",
        clearEndDate: "Clear end date",
        required: "Required",
        
        // 数据传输
        dataTransfer: "Data Transfer",
        shareMode: "Share Data",
        receiveMode: "Receive Data",
        currentDataSummary: "Current Data Summary",
        shareSettings: "Share Settings",
        shareFirewallNotice: "⚠️ Starting or stopping sharing configures the firewall and requires administrator privileges",
        startShare: "Start Sharing",
        stopShare: "Stop Sharing",
        shareStatus: "Sharing Status",
        ipAddress: "IP Address: ",
        port: "Port: ",
        sharingData: "Sharing Data",
        scanDevice: "Scan Devices",
        scanNetworkDevice: "Scan Local Network Devices",
        availableDevices: "Available Devices",
        noDevicesFound: "No devices found",
        receivedDataPreview: "Received Data Preview",
        waitingForData: "Waiting to receive data...",
        importWarning: "⚠️ Warning: Importing will overwrite all current data. Please backup first!",
        confirmImport: "Confirm Import",
        cancelImport: "Cancel",

        // 数据同步
        dataSync: "Data Sync",
        syncType: "Data Sync Type",
        syncTypeJianguoyun: "JianGuoYun",
        syncTypeCustom: "Custom",
        url: "Server URL*",
        account: "Account*",
        password: "Password*",
        filepath: "File Path*",
        firstSyncMode: "First Sync Mode",
        firstSyncModeRemote: "Remote Overwrite Local",
        firstSyncModeLocal: "Local Overwrite Remote",
        webdavUrlPlaceholder: "Please enter the WebDAV server address",
        webdavAccountPlaceholder: "Please enter your email address",
        webdavPasswordPlaceholder: "Please enter the app-specific password",
        webdavPathPlaceholder: "Please enter the remote sync directory, e.g. /todolist",
        testConnection: "Test Connection",
        saveConfiguration: "Save Configuration",
        autoSyncNotice: "⚠️ When there is a mapping relationship between the cloud path and the local data storage path, please do not enable cloud sync to avoid redundant data updates. For automatic sync rules after the initial sync: if there is a data update on any endpoint, the data will be automatically synced to other endpoints within 15 seconds.",
    }
};

// 导出到全局
if (typeof window !== 'undefined') {
    window.Languages = Languages;
    logger.info('Languages config loaded successfully');
}